### ISSUE TITLE
error at imap.enable(UTF8CAP)

### ISSUE THREAD

**Issue by uselpa** [disappearinjon/swiftbar-imap-counter#1]
Good morning,

first of all, thanks for your project, it is exactly what I needed right now ;-)

In `startImap`, a remark says _Enable the UTF-8 capability, but ignore any errors_; however, the errors are NOT ignored.

I'm not familiar with pull requests, but my local fix was to use a try/except clause like so:
```
# Enable the UTF-8 capability, but ignore any errors
try:
    imap.enable(UTF8CAP)
except:
    pass
```

Regards,
-Patrick

**Comment by disappearinjon** [comment]
Patrick,

Thanks for the feedback!

The "errors" I'm trying to ignore are in the return values from the command--I certainly wasn't expecting an exception to be raised.

I'd love to wrap that, but I'm not entirely comfortable with a bare except.  Can you send me the stack trace & exception for the failure with the original code?

Thanks again,
Jon
--
Web: twoideas.org / Twitter: @disappearinjon / Mailing list: bit.ly/difficultsf


On Tue, May 18, 2021, at 11:29 PM, uselpa wrote:
> 

> Good morning,

> first of all, thanks for your project, it is exactly what I needed right now ;-)

> In `startImap`, a remark says *Enable the UTF-8 capability, but ignore any errors*; however, the errors are NOT ignored.

> I'm not familiar with pull requests, but my local fix was to use a try/except clause like so:

> `# Enable the UTF-8 capability, but ignore any errors
try:
    imap.enable(UTF8CAP)
except:
    pass
`

**Comment by uselpa** [comment]
Jon,
You are right of course, the specific exception to catch is `imaplib.IMAP4.error`.
Please see also the attached screenshot.
Regards, 
-Patrick

<img width="473" alt="Screenshot 2021-05-20 at 11 06 44" src="https://user-images.githubusercontent.com/54102656/118953146-d9f87280-b95c-11eb-8af5-1fd496fd1dd7.png">

**Comment by disappearinjon** [comment]
Patrick,

I've posted an updated version with a fix. Please go ahead and double-check that my fix works for you.

Jon

**Comment by uselpa** [comment]
Hello Jon,
yes it does, thanks.
Regards,
-Patrick

**Comment by disappearinjon** [comment]
Thanks for double-checking! Closing this issue!
